#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/media/data/executable/wine/AmazonMusic
export LD_PRELOAD=

exec 1>/dev/null 2>/dev/null

wine 'C:\users\nyarla\AppData\Local\Amazon Music\Amazon Music.exe' &
waitPID=$!

test -n "${waitPID}" && wait $waitPID

wineserver -k

exit 0
