#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/run/media/nyarla/data/local/wine/AmazonMusic
export LD_PRELOAD=

wine 'C:\users\nyarla\AppData\Local\Amazon Music\Amazon Music.exe' &
waitPID=$!

test -n "${waitPID}" && wait $waitPID

wineserver -k

exit 0
