#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/run/media/nyarla/data/local/daw/daw/plugins/Arturia
export LD_PRELOAD=

wine 'C:\Program Files (x86)\Arturia\Arturia Software Center\Arturia Software Center.exe' &
waitPID=$!

test -n "${waitPID}" && wait $waitPID

wineserver -k

exit 0
