#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/run/media/nyarla/data/local/daw/daw/plugins/Steinberg
export LD_PRELOAD=

wine 'C:\Program Files (x86)\eLicenser\eLCC\eLCC.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
