#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/run/media/nyarla/data/local/daw/daw/daw/FLStudio
export LD_PRELOAD=

chmod +w $WINEPREFIX/drive_c/windows/system32/wineasio.dll
cp /run/current-system/sw/lib/wine/x86_64-unix/wineasio.dll.so \
  $WINEPREFIX/drive_c/windows/system32/wineasio.dll

wine64 regsvr32 wineasio.dll

wine 'C:\Program Files\Image-Line\FL Studio 20\FL64.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
