#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/run/media/nyarla/data/local/daw/daw/plugins/IKMultimedia
export LD_PRELOAD=

wine 'C:\Program Files\IK Multimedia\IK Product Manager\IK Product Manager.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
