#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/media/data/executable/wine/Kindle
export LD_PRELOAD=

wine 'C:\Program Files (x86)\Amazon\Kindle\Kindle.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
