#!/usr/bin/env bash

set -euo pipefail

cd $HOME/Applications/Wine/Kindle

wine-staging wine 'C:\Program Files\Amazon\Kindle\Kindle.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wine-staging wineboot --shutdown

exit 0
