#!/usr/bin/env sh

set -euo pipefail

export WINEPREFIX=/media/data/executable/wine/MP3Tag
export LD_PRELOAD=

wine 'C:\Program Files (x86)\Mp3tag\Mp3tag.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
