#!/usr/bin/env bash

set -euo pipefail

cd $HOME/Applications/Wine/MP3TAG


wine-staging wine 'C:\Program Files\Mp3tag\Mp3tag.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wine-staging wineboot --shutdown

exit 0
