#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/home/nyarla/Applications/Wine/MP3TAG
export LD_PRELOAD=

wine 'C:\Program Files\Mp3tag\Mp3tag.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0
