#!/usr/bin/env bash

set -euo pipefail
  
export WINEPREFIX=/run/media/nyarla/data/local/daw/daw/plugins/NI
export LD_PRELOAD=

wine 'C:\Program Files\Native Instruments\Native Access\Native Access.exe' &
waitPID=$!

test -n "$waitPID" && wait $waitPID

wineserver -k

exit 0

