#!/usr/bin/env bash

set -euo pipefail

export WINEPREFIX=/media/data/DAW/DAW/OrbComposerProS
export LD_PRELOAD=

test ! -e $WINEPREFIX/drive_c/windows/system32/wineasio.dll \
  || chmod +w $WINEPREFIX/drive_c/windows/system32/wineasio.dll
cp /run/current-system/sw/lib/wine/x86_64-unix/wineasio.dll.so \
  $WINEPREFIX/drive_c/windows/system32/wineasio.dll

wine64 regsvr32 wineasio.dll

pkill -9 jackd || true
pasuspender -- jackd -R -dalsa -dplughw:USB -r96000 -p512 -n3 &

AudioGridderServer &

sleep 3

wine 'C:\Program Files\Hexachords\Orb Composer 1-5\Pro\Orb Composer S.exe' &
orbPID=$!

wait $orbPID

pgrep AudioGridder | xargs -I{} kill {}
pgrep jackd | xargs -I{} kill -9 {}

wineserver -k || true

exit 0
