#!/usr/bin/env sh

export WINEPREFIX=/run/media/nyarla/src/local/daw/daw/deCoda
export LD_PRELOAD=
export PIPEWIRE_LATENCY=512/96000

cd $WINEPREFIX

# wineasio.dll
chmod +w $WINEPREFIX/drive_c/windows/system32/wineasio.dll
cp /run/current-system/sw/lib/wine/x86_64-unix/wineasio.dll.so \
  $WINEPREFIX/drive_c/windows/system32/wineasio.dll

wine64 regsvr32 wineasio.dll

# FL Studio
exec wine explorer 'C:\Program Files\zplane\deCoda\deCoda.exe'
