#!/usr/bin/env bash

mirror() {
  local src=$1 dest=$2

  if test -d "${src:-}" && test -d "${dest:-}" ; then
    rsync -av --delete $src $dest
  fi
}

main() {
  for dir in active apps data tmp ; do
    mirror /data/$dir/ /run/media/nyarla/RAID/$dir/
  done

  if test -d /data/tmp && test -e /etc/restic/credentials ; then
    source /etc/restic/credentials
    cd /data
    restic backup --exclude-file=/etc/restic/resticignore active apps data tmp
  fi

  exit 0
}

main
