#!/usr/bin/env bash

set -euo pipefail

cleanup-snapshot() {
  local config=$1 path=$2

  cd $path && \ls | xargs -I{} snapper -c $config delete {}
}

cleanup-snapshot etc-nixos /persist/etc/nixos/.snapshots
cleanup-snapshot home-nyarla /persist/home/nyarla/.snapshots
cleanup-snapshot home-nyarla-applications /persist/home/nyarla/Applications/.snapshots
cleanup-snapshot home-nyarla-programming /persist/home/nyarla/Programming/.snapshots
cleanup-snapshot var-lib /persist/var/lib/.snapshots

sudo mkdir -p /tmp/btrfs
sudo mount /dev/mapper/nixos /tmp/btrfs

cd /tmp/btrfs
sudo btrfs scrub start .
