#!/usr/bin/env bash

DTM=/run/media/nyarla/data/local/daw/daw

for dir in $HOME/local/wine $DTM/daw $DTM/plugins; do
  for prefix in $(ls "${dir}"); do
      cwd=$(pwd)

      cd "${dir}/${prefix}"
      echo $(pwd)
      wine-run wineboot -u
      wine-run wineserver -k
      cd $cwd
  done
done
