#!/usr/bin/env bash

set -euo pipefail

waydroid session stop

env SHELL=/bin/sh pkexec sh -c '
    sudo umount /persist/home/nyarla/.local/share/waydroid/data/media/0/Music
    sudo umount /persist/home/nyarla/.local/share/waydroid/data/media/0/Download
  '
