#!/usr/bin/env bash

set -euo pipefail
grep -qF 'Android with user 0 is ready' <(waydroid show-full-ui 2>&1) \
  && env SHELL=/bin/sh pkexec sh -c '
    sudo mount --bind /backup/Music /persist/home/nyarla/.local/share/waydroid/data/media/0/Music
    sudo mount --bind /persist/home/nyarla/Downloads /persist/home/nyarla/.local/share/waydroid/data/media/0/Download
  '
