#!/usr/bin/env bash

set -euo pipefail

weston &
westonPID=$!

export XDG_SESSION_TYPE=wayland
export XDG_DATA_HOME=/persist/home/nyarla/.local/share
export WAYLAND_DISPLAY=wayland-1

while test ! -e /run/user/$(id -u)/wayland-1 ; do
  sleep 1
done

bash "$(dirname "$0")/waydroid-start"

wait $westonPID

bash "$(dirname "$0")/waydroid-stop"
