#!/usr/bin/env bash

set -euo pipefail

main() {
  test -d ~/.config/zrythm.d || mkdir ~/.config/zrythm.d

  for dir in audiogridder dconf fcitx ibus pulse ; do
    test -L ~/.config/zrythm.d/"${dir}" || ln -sf ~/.config/"${dir}" ~/.config/zrythm.d/"${dir}"
  done

  env XDG_CONFIG_HOME=~/.config/zrythm.d zrythm_launch
}

main
